[package]
name = "libarch"
version = "0.1.0"
edition = "2024"

[lib]
name = "arch"
path = "src/lib.rs"
test = false
doctest = false
bench = false

[dependencies]
bitflags = "2.3.2"
bit_field = "0.10.1"
